---
apiVersion: v1
kind: Template
metadata:
  name: prometheus-kafka-consumer-group-exporter
parameters:
- name: IMAGE
  value: ""
- name: IMAGE_TAG
  value: ""
- name: BOOTSTRAP_SERVERS
  value: ""
- name: AUTO_OFFSET_RESET
  value: "latest"
- name: GROUP_ID
  value: ""
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: prometheus-kafka-consumer-group-exporter-config
    labels:
      app: kafka-lag-exporter
  data:
    consumer_config.ini: |
      bootstrap_servers=${BOOTSTRAP_SERVERS}
      auto_offset_reset=${AUTO_OFFSET_RESET}
      group_id=${GROUP_ID}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kafka-lag-exporter
    labels:
      app: kafka-lag-exporter
  spec:
    replicas: 1
    minReadySeconds: 5
    progressDeadlineSeconds: 600
    revisionHistoryLimit: 3
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: kafka-lag-exporter
    template:
      metadata:
        labels:
          app: kafka-lag-exporter
      spec:
        volumes:
        - configMap:
            defaultMode: 420
            name: prometheus-kafka-consumer-group-exporter-config
          name: prometheus-kafka-consumer-group-exporter-config
        containers:
        - name: kafka-lag-exporter-stage
          image: ${IMAGE}:${IMAGE_TAG}
          readinessProbe:
            tcpSocket:
              port: 9208
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9208
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 10
          env:
          - name: CONSUMER_CONFIG
            value: /data/consumer_config.ini
          - name: APP_FILE
            value: prometheus_kafka_consumer_group_exporter/__main__.py
          ports:
          - containerPort: 9208
            protocol: TCP
          volumeMounts:
          - mountPath: /data
            name: prometheus-kafka-consumer-group-exporter-config
- apiVersion: v1
  kind: Service
  metadata:
    name: kafka-lag-exporter
    labels:
      app: kafka-lag-exporter
  spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      name: metrics
      port: 9208
      targetPort: 9208
    selector:
      app: kafka-lag-exporter

